services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    restart: always

  backend:
    image: joonatanaatos/kuka-soittaa-backend:latest
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
    ports:
      - "3000:3000"
    depends_on:
      - database
    volumes:
      - uploads:/usr/src/app/uploads
    restart: always
  
  admin-panel:
    image: joonatanaatos/kuka-soittaa-admin-panel:latest
    ports:
      - "8080:8080"
    restart: always

volumes:
  data:
    name: kuka-soittaa-data
  uploads:
    name: kuka-soittaa-uploads
